In [16]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [17]:
df = load_wine()
df

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [18]:
X = df.data
y = df.target

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=1,stratify=y)

In [20]:
y_train

array([2, 0, 2, 1, 2, 0, 1, 0, 1, 1, 1, 0, 2, 1, 0, 0, 0, 1, 2, 1, 2, 2,
       1, 2, 2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 2, 1, 0, 1, 2, 2, 1, 1, 0, 0,
       0, 2, 1, 2, 0, 1, 1, 2, 0, 1, 1, 1, 2, 0, 0, 2, 1, 1, 2, 0, 0, 1,
       2, 0, 1, 0, 1, 2, 1, 1, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       1, 0, 1, 1, 2, 2, 1, 2, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0,
       0, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 2, 2, 0, 0, 1, 0, 1, 2, 1,
       0, 0, 1, 1, 1, 2, 0, 2, 0, 2])

In [21]:
dt = DecisionTreeClassifier(criterion='entropy',max_depth=1,random_state=1)
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=1, random_state=1)

In [22]:
print(" Test Score ", dt.score(X_test, y_test))
print("Training Score ", dt.score(X_train, y_train))

 Test Score  0.6111111111111112
Training Score  0.5985915492957746


In [23]:
from sklearn.ensemble import AdaBoostClassifier
classifier = DecisionTreeClassifier(criterion='entropy',max_depth=1,random_state=1)
abdclassifier = AdaBoostClassifier(base_estimator=classifier,algorithm = 'SAMME.R',random_state= 1)

In [24]:
abdclassifier.fit(X_train,y_train)

print("Test score %3f" %abdclassifier.score(X_test,y_test))
print("Train Score %3f" %abdclassifier.score(X_train,y_train))

Test score 0.972222
Train Score 1.000000


In [25]:
from sklearn.metrics import classification_report

y_pred = abdclassifier.predict(X_test)
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        12
           1       0.93      1.00      0.97        14
           2       1.00      1.00      1.00        10

    accuracy                           0.97        36
   macro avg       0.98      0.97      0.97        36
weighted avg       0.97      0.97      0.97        36



In [26]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_pred,y_test))

[[11  0  0]
 [ 1 14  0]
 [ 0  0 10]]
