In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = load_wine()
X = df.data
y = df.target

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1,stratify=y)

In [5]:
dt = DecisionTreeClassifier(criterion='gini',max_depth=1,random_state=1)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=1, random_state=1)

In [6]:
print("test score: %3f" %dt.score(X_test, y_test))
print("train score: %3f" %dt.score(X_train, y_train))

test score: 0.666667
train score: 0.704225


In [9]:
from sklearn.ensemble import AdaBoostClassifier

adbc = AdaBoostClassifier(base_estimator=dt,algorithm='SAMME.R',random_state=1)
adbc.fit(X_train,y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1,
                                                         random_state=1),
                   random_state=1)

In [10]:
print("test score: ", adbc.score(X_test, y_test))
print("train score: ", adbc.score(X_train, y_train))

test score:  0.9166666666666666
train score:  0.9788732394366197


In [11]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = adbc.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92        12
           1       0.87      0.93      0.90        14
           2       1.00      0.90      0.95        10

    accuracy                           0.92        36
   macro avg       0.93      0.92      0.92        36
weighted avg       0.92      0.92      0.92        36



In [12]:
print(confusion_matrix(y_pred,y_test))

[[11  1  0]
 [ 1 13  1]
 [ 0  0  9]]
